/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.poc.avro.serde;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Message extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Message\",\"namespace\":\"org.poc.avro.serde\",\"fields\":[{\"name\":\"mesgid\",\"type\":\"string\"},{\"name\":\"Dtls\",\"type\":{\"type\":\"record\",\"name\":\"Dtls\",\"fields\":[{\"name\":\"sender\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"string\"},{\"name\":\"subject\",\"type\":\"string\"},{\"name\":\"cc\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence mesgid;
  @Deprecated public org.poc.avro.serde.Dtls Dtls;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Message() {}

  /**
   * All-args constructor.
   */
  public Message(java.lang.CharSequence mesgid, org.poc.avro.serde.Dtls Dtls) {
    this.mesgid = mesgid;
    this.Dtls = Dtls;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return mesgid;
    case 1: return Dtls;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: mesgid = (java.lang.CharSequence)value$; break;
    case 1: Dtls = (org.poc.avro.serde.Dtls)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'mesgid' field.
   */
  public java.lang.CharSequence getMesgid() {
    return mesgid;
  }

  /**
   * Sets the value of the 'mesgid' field.
   * @param value the value to set.
   */
  public void setMesgid(java.lang.CharSequence value) {
    this.mesgid = value;
  }

  /**
   * Gets the value of the 'Dtls' field.
   */
  public org.poc.avro.serde.Dtls getDtls() {
    return Dtls;
  }

  /**
   * Sets the value of the 'Dtls' field.
   * @param value the value to set.
   */
  public void setDtls(org.poc.avro.serde.Dtls value) {
    this.Dtls = value;
  }

  /** Creates a new Message RecordBuilder */
  public static org.poc.avro.serde.Message.Builder newBuilder() {
    return new org.poc.avro.serde.Message.Builder();
  }
  
  /** Creates a new Message RecordBuilder by copying an existing Builder */
  public static org.poc.avro.serde.Message.Builder newBuilder(org.poc.avro.serde.Message.Builder other) {
    return new org.poc.avro.serde.Message.Builder(other);
  }
  
  /** Creates a new Message RecordBuilder by copying an existing Message instance */
  public static org.poc.avro.serde.Message.Builder newBuilder(org.poc.avro.serde.Message other) {
    return new org.poc.avro.serde.Message.Builder(other);
  }
  
  /**
   * RecordBuilder for Message instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Message>
    implements org.apache.avro.data.RecordBuilder<Message> {

    private java.lang.CharSequence mesgid;
    private org.poc.avro.serde.Dtls Dtls;

    /** Creates a new Builder */
    private Builder() {
      super(org.poc.avro.serde.Message.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.poc.avro.serde.Message.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.mesgid)) {
        this.mesgid = data().deepCopy(fields()[0].schema(), other.mesgid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Dtls)) {
        this.Dtls = data().deepCopy(fields()[1].schema(), other.Dtls);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Message instance */
    private Builder(org.poc.avro.serde.Message other) {
            super(org.poc.avro.serde.Message.SCHEMA$);
      if (isValidValue(fields()[0], other.mesgid)) {
        this.mesgid = data().deepCopy(fields()[0].schema(), other.mesgid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Dtls)) {
        this.Dtls = data().deepCopy(fields()[1].schema(), other.Dtls);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'mesgid' field */
    public java.lang.CharSequence getMesgid() {
      return mesgid;
    }
    
    /** Sets the value of the 'mesgid' field */
    public org.poc.avro.serde.Message.Builder setMesgid(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.mesgid = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'mesgid' field has been set */
    public boolean hasMesgid() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'mesgid' field */
    public org.poc.avro.serde.Message.Builder clearMesgid() {
      mesgid = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'Dtls' field */
    public org.poc.avro.serde.Dtls getDtls() {
      return Dtls;
    }
    
    /** Sets the value of the 'Dtls' field */
    public org.poc.avro.serde.Message.Builder setDtls(org.poc.avro.serde.Dtls value) {
      validate(fields()[1], value);
      this.Dtls = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'Dtls' field has been set */
    public boolean hasDtls() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'Dtls' field */
    public org.poc.avro.serde.Message.Builder clearDtls() {
      Dtls = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public Message build() {
      try {
        Message record = new Message();
        record.mesgid = fieldSetFlags()[0] ? this.mesgid : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.Dtls = fieldSetFlags()[1] ? this.Dtls : (org.poc.avro.serde.Dtls) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
